name: GitHub Actions Demo

run-name: ${{ github.actor }} is testing out GitHub Actions

on: [push]

jobs:
  compile-run-each:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "This job's status is ${{ job.status }}."
      - run: sudo apt-get install openmpi-bin libopenmpi-dev libnetcdff-dev netcdf-bin
      - run: ls /usr/bin
      - name: Run the mpi_no_netcdf code
        run: |
          cd mpi_no_netcdf
          make
          mpiexec -np 2 ./run/ufsLand.exe
      - name: Run the netcdf code
        run: |
          cd netcdf
          make
          ./test_netcdf.exe
          ncdump blah.nc
      - name: Run the mpi_netcdf code
        run: |
          cd mpi_netcdf
          make
          mpiexec -np 2 ./run/ufsLand.exe
          ncdump test.nc
    
