name: GitHub Actions: mpi_netcdf

on: [push]

jobs:

  set-environment:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install openmpi-bin libopenmpi-dev libnetcdf-mpi-dev netcdf-bin
      - run: dpkg -L libnetcdf-mpi-dev
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Run the mpi_netcdf code
        run: |
          cd mpi_netcdf
          make
          mpiexec -np 2 ./run/ufsLand.exe
          ls
          ls run
          ncdump ./run/test.nc
    
