name: GitHub Actions netcdf

on: [push]

jobs:

  build-run:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install libnetcdf-mpi-dev netcdf-bin
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Run the netcdf code
        run: |
          cd netcdf
          make
          ./test_netcdf.exe
          ncdump blah.nc
